(() => {
 const sampleSources=[
  {name:'Guía de trabajo en altura',source:'Procedimiento interno · PDF',topic:'Trabajo en altura',review:'2026-09-12',status:'Publicado'},
  {name:'Ficha técnica · Respirador P100',source:'Fabricante · PDF',topic:'Protección respiratoria',review:'2026-09-08',status:'Publicado'},
  {name:'Procedimiento bloqueo y etiquetado',source:'Manual interno · DOCX',topic:'Riesgo eléctrico',review:'',status:'Pendiente'},
  {name:'Preguntas frecuentes sobre EPP',source:'Contenido editorial · DOCX',topic:'General',review:'2026-09-02',status:'Publicado'}
 ];
 const $=s=>document.querySelector(s),fmtDate=v=>v?new Date(`${v}T12:00:00`).toLocaleDateString('es-AR',{day:'2-digit',month:'short',year:'numeric'}):'—';
 const modal=$('#modal');if(!modal)return;
 const close=()=>modal.classList.remove('open');$('#cancel').addEventListener('click',close);modal.addEventListener('click',e=>{if(e.target===modal)close()});
 const products=()=>Prevenclick.read('prevenclick-products',Prevenclick.starterProducts);
 function renderProducts(){const rows=$('#rows');if(!rows)return;const query=$('#search').value.toLowerCase(),category=$('#category').value,list=products();const cats=[...new Set(list.map(p=>p.category))];$('#category').innerHTML='<option value="">Todas las categorías</option>'+cats.map(c=>`<option>${c}</option>`).join('');$('#category').value=category;const filtered=list.filter(p=>(!query||`${p.name} ${p.category}`.toLowerCase().includes(query))&&(!category||p.category===category));rows.innerHTML=filtered.map(p=>`<tr><td><span class="item-name">${p.name}</span><span class="item-sub">Ficha de producto</span></td><td>${p.category}</td><td>${Prevenclick.money(Number(p.price)||0)}</td><td>${p.stock}</td><td><span class="status ${p.status==='Publicado'?'':'pending'}">${p.status}</span></td></tr>`).join('')||'<tr><td colspan="5">No encontramos productos con esos filtros.</td></tr>';$('#metric-total').textContent=list.length;$('#metric-stock').textContent=list.filter(p=>Number(p.stock)>0).length;}
 $('#search')?.addEventListener('input',renderProducts);$('#category')?.addEventListener('change',renderProducts);$('#add-product')?.addEventListener('click',()=>modal.classList.add('open'));$('#product-form')?.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const list=products();list.unshift({...data,price:Number(data.price),stock:Number(data.stock),status:'Publicado'});Prevenclick.write('prevenclick-products',list);e.currentTarget.reset();close();renderProducts()});renderProducts();
 const sourceKey='prevenclick-sources',sources=()=>Prevenclick.read(sourceKey,sampleSources);
 function renderSources(){const rows=$('#source-rows');if(!rows)return;const query=$('#source-search').value.toLowerCase(),state=$('#source-state').value,list=sources(),filtered=list.filter(s=>(!query||`${s.name} ${s.topic} ${s.source}`.toLowerCase().includes(query))&&(!state||s.status===state));rows.innerHTML=filtered.map(s=>`<tr><td><span class="item-name">${s.name}</span><span class="item-sub">${s.source}${s.owner?` · ${s.owner}`:''}</span></td><td>${s.topic}</td><td>${fmtDate(s.review)}</td><td><span class="status ${s.status==='Publicado'?'':'pending'}">${s.status}</span></td></tr>`).join('')||'<tr><td colspan="4">No encontramos fuentes con esos filtros.</td></tr>';$('#active-count').textContent=list.filter(s=>s.status==='Publicado').length;$('#pending-count').textContent=list.filter(s=>s.status==='Pendiente').length;}
 $('#source-search')?.addEventListener('input',renderSources);$('#source-state')?.addEventListener('change',renderSources);$('#add-source')?.addEventListener('click',()=>modal.classList.add('open'));$('#source-form')?.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const list=sources();list.unshift({...data,status:'Pendiente'});Prevenclick.write(sourceKey,list);e.currentTarget.reset();close();renderSources()});renderSources();
})();
